---
- name: Create Tomcat User
  user: name=tomcat shell=/bin/bash home=/opt/tomcat createhome=no state=present system=yes
  tags: tomcat

- name: Retrieve Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-{{major_version}}/v{{major_version}}.{{minor_version}}.{{min_version}}/bin/apache-tomcat-{{major_version}}.{{minor_version}}.{{min_version}}.tar.gz dest=/opt/
  tags: tomcat

- name: Unpack Tomcat
  command: tar -xzf /opt/apache-tomcat-{{major_version}}.{{minor_version}}.{{min_version}}.tar.gz chdir=/opt
  tags: tomcat

- name: Own tomcat by tomcat
  file: state=directory path=/opt/apache-tomcat-{{major_version}}.{{minor_version}}.{{min_version}} owner=tomcat group=tomcat recurse=yes
  tags: tomcat

- name: Link to /opt/tomcat
  file: state=link src=/opt/apache-tomcat-{{major_version}}.{{minor_version}}.{{min_version}} path=/opt/tomcat owner=tomcat group=tomcat
  tags: tomcat

- name: Link Init Script
  copy: src=tomcat_init dest=/etc/init.d/tomcat mode=0755 owner=root group=root
  notify: start tomcat
  tags: tomcat
